// triangulation_presets.js — a library of standard ideal triangulations.
//
// Closed-surface fixtures are faithful copies of the repo's
// skein_sphere/triangulation.py class methods (edge-index data verified
// entry-by-entry against Python, incl. sigma() and flip↔mutation).  Polygon
// (disk) charts are generated by `fanPolygon(n)`, reproducing
// BorderedTriangulation.fan_polygon(n) → Triangulation.from_bordered_slots.
//
// A genus-1 example (the Möbius–Kantor / once-punctured-torus-style chart) is
// included so the developed fundamental-polygon-with-identifications view has a
// non-spherical case to show.

import { makeTriangulation } from "./triangulation.js";

// ── The fan triangulation of an n-gon (disk with n boundary marked points) ──
//
// Diagonals (0, d) for d = 2 … n−2 come first (edge ids 0 … n−4); then the n
// boundary sides.  Numbering reproduces fan_polygon(n) exactly, so σ indexing
// and flip-node ids match the Python chart.
export function fanPolygon(n) {
  if (n < 3) throw new Error("a polygon needs n ≥ 3 marked points");
  const edges = [];
  const edgeId = new Map(); // "u,v" -> id
  const put = (u, v) => {
    const key = `${Math.min(u, v)},${Math.max(u, v)}`;
    const id = edges.length;
    edges.push([Math.min(u, v), Math.max(u, v)]);
    edgeId.set(key + `#${id}`, id); // allow the loop below to address by construction
    return id;
  };
  // diagonals (0,2)…(0,n-2) → ids 0 … n-4
  const diagId = new Map();
  for (let d = 2; d <= n - 2; d++) diagId.set(d, put(0, d));
  // boundary sides: (0,1) first, then (i,i+1) for i=1..n-2, then (0,n-1)
  const sideId = new Map();
  sideId.set("0,1", put(0, 1));
  for (let i = 1; i <= n - 2; i++) sideId.set(`${i},${i + 1}`, put(i, i + 1));
  sideId.set(`0,${n - 1}`, put(0, n - 1));

  const eid = (u, v) => {
    if (u === 0 && v >= 2 && v <= n - 2) return diagId.get(v);
    if (v === 0 && u >= 2 && u <= n - 2) return diagId.get(u);
    const a = Math.min(u, v), b = Math.max(u, v);
    if (a === 0 && b === 1) return sideId.get("0,1");
    if (a === 0 && b === n - 1) return sideId.get(`0,${n - 1}`);
    return sideId.get(`${a},${b}`);
  };
  // triangle i (i=0..n-3) on vertices (0, i+1, i+2), edges opposite each corner
  const triangleEdges = [];
  for (let i = 0; i <= n - 3; i++) {
    triangleEdges.push([eid(0, i + 1), eid(i + 1, i + 2), eid(0, i + 2)]);
  }
  return makeTriangulation({
    name: `Polygon P${n}`, nPunctures: n, edges, triangleEdges, kind: "bordered",
  });
}

// ── Named closed fixtures (faithful to triangulation.py) ──────────────────

const CLOSED = {
  tetrahedron: {
    name: "Tetrahedron S²₀,₄", nPunctures: 4,
    edges: [[0, 1], [0, 2], [0, 3], [1, 2], [1, 3], [2, 3]],
    triangleEdges: [[0, 3, 1], [0, 2, 4], [1, 5, 2], [3, 4, 5]],
  },
  bipyramid: {
    name: "Bipyramid S²₀,₅", nPunctures: 5,
    edges: [[0, 1], [0, 2], [0, 3], [0, 4], [1, 2], [1, 3], [1, 4], [2, 3], [2, 4]],
    triangleEdges: [[0, 5, 2], [4, 7, 5], [1, 2, 7], [0, 3, 6], [4, 6, 8], [1, 8, 3]],
  },
  octahedron: {
    name: "Octahedron S²₀,₆", nPunctures: 6,
    edges: [[0, 1], [0, 3], [0, 4], [0, 5], [1, 2], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5], [3, 4], [3, 5]],
    triangleEdges: [[0, 5, 2], [4, 8, 5], [7, 10, 8], [1, 2, 10], [0, 3, 6], [4, 6, 9], [7, 9, 11], [1, 11, 3]],
  },
  sausage: {
    name: "Cluster sausage S²₀,₅", nPunctures: 5,
    edges: [[0, 2], [0, 2], [2, 3], [2, 3], [2, 2], [1, 2], [0, 1], [2, 4], [3, 4]],
    triangleEdges: [[0, 1, 4], [2, 3, 4], [0, 5, 6], [6, 5, 1], [2, 7, 8], [8, 7, 3]],
  },
};

// The once-punctured torus (genus 1) = N=2* SU(2): one vertex, three
// self-loop edges, two triangles both reading (0,1,2) ccw.  Faithful to
// skein_annulus_kalg.py's `Triangulation.from_edge_data(1, [(0,0)*3],
// [(0,1,2),(0,1,2)])` (asserted genus 1 there).  Its σ is the Markov quiver
// [[0,2,−2],[−2,0,2],[2,−2,0]].  This is the classic "square with opposite
// sides identified" fundamental polygon, diagonal triangulated — the flagship
// case for the developed identified-sides view.
const TORUS = {
  name: "Once-punctured torus T²₁,₁", nPunctures: 1,
  edges: [[0, 0], [0, 0], [0, 0]],
  triangleEdges: [[0, 1, 2], [0, 1, 2]],
};

// The Csaszar (K₇) ideal triangulation of the 7-punctured torus (genus 1):
// the complete graph K₇ embedded on the torus with all 14 faces triangles,
// faces (i, i+1, i+3) and (i, i+3, i+2) over Z₇.  Verified genus 1 in Python.
function csaszarTorus() {
  const edgeId = new Map();
  const edges = [];
  const eid = (a, b) => {
    const key = `${Math.min(a, b)},${Math.max(a, b)}`;
    if (!edgeId.has(key)) { edgeId.set(key, edges.length); edges.push([Math.min(a, b), Math.max(a, b)]); }
    return edgeId.get(key);
  };
  const tris = [];
  const face = (a, b, c) => tris.push([eid(a, b), eid(b, c), eid(c, a)]);
  for (let i = 0; i < 7; i++) {
    face(i % 7, (i + 1) % 7, (i + 3) % 7);
    face(i % 7, (i + 3) % 7, (i + 2) % 7);
  }
  return makeTriangulation({ name: "Csaszar torus T²₁,₇", nPunctures: 7, edges, triangleEdges: tris, kind: "closed" });
}

// SU(2)+N_f bordered disks (faithful to skein_su2_nf{2,3}_disk).  Their
// boundary components are encoded as self-loop edges (an irregular puncture /
// n-boundary); interior vertices are regular punctures.  Best viewed as the
// dual exchange quiver.
const NF2_DISK = {
  name: "SU(2) N_f=2 disk", nPunctures: 3,
  edges: [[0, 1], [0, 2], [0, 1], [1, 2], [0, 0]],
  triangleEdges: [[0, 3, 1], [1, 3, 2], [2, 0, 4]],
};
const NF3_DISK = {
  name: "SU(2) N_f=3 disk", nPunctures: 4,
  edges: [[0, 2], [1, 2], [0, 3], [1, 3], [2, 3], [0, 1], [0, 1]],
  triangleEdges: [[5, 1, 0], [6, 2, 3], [0, 4, 2], [3, 4, 1]],
};

// ── The public catalogue ──────────────────────────────────────────────────
//
// Each entry: { key, group, label, note, build() }.  `note` gives the skein /
// physics reading so the panel can name the theory.

export const PRESETS = [
  { key: "p4", group: "Polygons (disks)", label: "Square P₄", note: "A_𝖖[T[A₁,A₃]]-adjacent; the U(1) square (SQED₁)", build: () => fanPolygon(4) },
  { key: "p5", group: "Polygons (disks)", label: "Pentagon P₅", note: "A_𝖖[T[A₁,A₂]] — the pentagon (Argyres–Douglas A₂)", build: () => fanPolygon(5) },
  { key: "p6", group: "Polygons (disks)", label: "Hexagon P₆", note: "A_𝖖[T[A₁,A₃]] — the U(1) hexagon", build: () => fanPolygon(6) },
  { key: "p7", group: "Polygons (disks)", label: "Heptagon P₇", note: "A_𝖖[T[A₁,A₄]] — the heptagon", build: () => fanPolygon(7) },
  { key: "p8", group: "Polygons (disks)", label: "Octagon P₈", note: "A_𝖖[T[A₁,A₅]] — the U(1) octagon", build: () => fanPolygon(8) },
  { key: "p9", group: "Polygons (disks)", label: "Nonagon P₉", note: "A_𝖖[T[A₁,A₆]] — the nonagon", build: () => fanPolygon(9) },

  { key: "tetrahedron", group: "Closed spheres S²₀,ₙ", label: "Tetrahedron S²₀,₄", note: "SU(2) N_f=4 ≅ spherical DAHA(C∨C₁)", build: () => makeTriangulation(CLOSED.tetrahedron) },
  { key: "bipyramid", group: "Closed spheres S²₀,ₙ", label: "Bipyramid S²₀,₅", note: "SU(2)×SU(2) sausage", build: () => makeTriangulation(CLOSED.bipyramid) },
  { key: "octahedron", group: "Closed spheres S²₀,ₙ", label: "Octahedron S²₀,₆", note: "SU(2)³ sausage", build: () => makeTriangulation(CLOSED.octahedron) },
  { key: "sausage", group: "Closed spheres S²₀,ₙ", label: "Cluster sausage S²₀,₅", note: "self-loop (bifundamental) + multi-edge chart", build: () => makeTriangulation(CLOSED.sausage) },

  { key: "nf2disk", group: "Bordered (SU(2)+N_f)", label: "SU(2) N_f=2 disk", note: "1 boundary + 2 regular punctures", build: () => makeTriangulation(NF2_DISK) },
  { key: "nf3disk", group: "Bordered (SU(2)+N_f)", label: "SU(2) N_f=3 disk", note: "2 boundaries + 2 regular punctures", build: () => makeTriangulation(NF3_DISK) },

  { key: "torus", group: "Higher genus", label: "Once-punctured torus", note: "N=2* SU(2); the Markov quiver — square with opposite sides identified", build: () => makeTriangulation(TORUS) },
  { key: "csaszar", group: "Higher genus", label: "Csaszar torus T²₁,₇", note: "K₇ on the torus — 14 triangles, genus 1", build: () => csaszarTorus() },
];

// A custom polygon of arbitrary size (for the light-path input gesture).
export function customPolygon(n) { return fanPolygon(n); }

export function presetByKey(key) {
  const p = PRESETS.find((x) => x.key === key);
  return p ? p.build() : null;
}

// Group the catalogue for a tree/menu view.
export function presetGroups() {
  const groups = [];
  for (const p of PRESETS) {
    let g = groups.find((x) => x.group === p.group);
    if (!g) { g = { group: p.group, items: [] }; groups.push(g); }
    g.items.push(p);
  }
  return groups;
}
